name: gallery_saver_updated
description: Saves images and videos from network or temporary file to external storage. Both images and videos will be visible in Android Gallery and iOS Photos.
version: 3.0.1
homepage: https://corp.artisan.inc/

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  http: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: carnegietechnologies.gallery_saver
        pluginClass: GallerySaverPlugin
      ios:
        pluginClass: SwiftGallerySaverPlugin
